### ISSUE TITLE
5E cannot used

### ISSUE THREAD

**Issue by java17lzh** [EugeneSunrise/MixSoft#7]
There is no menu and it will be banned directly，Can I fix this problem？

**Comment by EugeneSunrise** [comment]
Only japanese 5E works(not chinese) and u need to change some variable's name's, slightly change the project to have a different pattern and crypt project with wmprotect or another protector + on 5e u need to play only with radar, without skin changer, aim, glow etc.... and play legit, dont beat 35k+ every game bro, okey brotha?

**Comment by java17lzh** [comment]
Thanks for your suggestion, but I guess it's not this problem, because when I started cheating, there was no response and I couldn't show the cheats

**Comment by java17lzh** [comment]
Is it safer to use static addresses instead of scanning signatures?

**Comment by EugeneSunrise** [comment]
> Is it safer to use static addresses instead of scanning signatures?

I think there is no difference
